name: sonomaneoutlet
description: Ini adalah aplikasi sonomane untuk outlet.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.8.9+10

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  rename: ^3.0.2
  firebase_storage: ^11.0.8
  firebase_core: ^2.4.0
  cloud_firestore: ^4.15.7
  image_picker: ^1.0.7
  uuid: ^4.3.3
  printing: ^5.9.3
  pdf: ^3.8.4
  firebase_auth: ^4.2.2
  dotted_line: ^3.1.0
  pretty_qr_code: ^3.2.1
  cached_network_image: ^3.2.3
  lottie: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  animate_do: ^3.0.2
  quickalert: ^1.0.1
  screenshot: ^2.1.0
  share_plus: ^7.2.2
  path_provider: ^2.0.14
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  motion_toast: ^2.6.5
  flutter_downloader: ^1.10.2
  cherry_toast: ^1.2.1
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_shimmer: ^2.1.2
  shimmer: ^3.0.0
  file_picker: ^6.1.1
  change_app_package_name: ^1.1.0
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  searchfield: ^0.9.6
  dotted_border: ^2.0.0+3
  pagination_flutter: ^0.0.8
  d_chart: ^2.6.3
  blue_thermal_printer: ^1.2.3
  bluetooth_enable_fork: ^0.1.6
  flutter_typeahead: ^4.8.0
  async: ^2.11.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
